
source 'http://rubygems.org'

gem 'rails', '2.3.14'

gem 'rest-client' # for rest-core
gem 'rest-core', :path => '../../'

group 'test' do
  gem 'rr'
  gem 'webmock'
end

platforms(:ruby) do
  gem 'yajl-ruby'
end

platforms(:jruby) do
  gem 'json'
  gem 'jruby-openssl'
end
