sudo: false
language: ruby

install: 'gem install bundler; bundle install --retry=3'
script: 'ruby -vr bundler/setup -S rake test'

matrix:
  include:
    - rvm: 2.3
      env: json_lib=json
    - rvm: 2.3
      env: json_lib=yajl
    - rvm: 2.4
      env: json_lib=json
    - rvm: 2.4
      env: json_lib=yajl
    - rvm: ruby-head
      env: json_lib=json
    - rvm: ruby-head
      env: json_lib=yajl
    - rvm: jruby
      env: JRUBY_OPTS=--debug
    - rvm: rbx

  allow_failures:
    - rvm: 2.4
      env: json_lib=json
    - rvm: 2.4
      env: json_lib=yajl
    - rvm: rbx
