script: 'git submodule update --init; bundle exec rake test:travis'

env:
  - 'RESTCORE=rest-graph'
  - 'RESTCORE=rails2'
  - 'RESTCORE=rails3'

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - rbx-2.0
  - jruby
